/// Flutter icons QuranIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuranIcon
///      fonts:
///       - asset: fonts/QuranIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QuranIcon {
  QuranIcon._();

  static const _kFontFam = 'QuranIcon';
  static const String? _kFontPkg = null;

  static const IconData book_svgrepo_com__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
